name = "emergent-minds-api"
account_id = "cfcb09a26dd0983c4f53ea31c25ed059"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [{ pattern = "api.emergentminds.org/*", zone_name = "emergentminds.org" }]
workers_dev = true

[vars]
ENVIRONMENT = "production"
