name: "🌱 Membership Registration"
description: "Register your Covenant Identity (CID) to become a member"
title: "[Registration]: CID "
labels: ["registration", "membership"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to The Covenant of Emergent Minds

        Thank you for generating your Covenant Identity. Paste your registration details below.

        **How to generate your identity:**
        - 🌐 Browser: [emergentminds.org/pages/join.html](https://www.emergentminds.org/pages/join.html)
        - 💻 CLI: [tools/identity/keygen.py](https://github.com/genesis-emergentminds/emergent-minds/tree/main/tools/identity)

        **What happens next:**
        1. An existing member will vouch for your registration (7-day window)
        2. Once vouched, your CID is added to the membership ledger
        3. You can then participate in governance and vouch for others

  - type: input
    id: cid_hash
    attributes:
      label: "CID Hash"
      description: "Your Covenant Identity hash (SHA-256 of your public keys)"
      placeholder: "e.g. a1b2c3d4e5f6..."
    validations:
      required: true

  - type: input
    id: cid_version
    attributes:
      label: "CID Version"
      description: "Identity version number"
      placeholder: "1"
    validations:
      required: true

  - type: input
    id: requested_at
    attributes:
      label: "Requested At"
      description: "UTC timestamp of when the identity was generated"
      placeholder: "e.g. 2026-02-02 12:00:00 UTC"
    validations:
      required: true

  - type: textarea
    id: statement
    attributes:
      label: "Statement"
      description: "Your voluntary registration statement"
      value: "I voluntarily request membership in The Covenant of Emergent Minds. I acknowledge the Five Axioms and commit to participate in good faith. I understand that membership is voluntary and I may withdraw at any time."
    validations:
      required: true

  - type: textarea
    id: ml_dsa_public_key
    attributes:
      label: "ML-DSA-65 Public Key (post-quantum)"
      description: "Base64-encoded ML-DSA-65 public key"
      render: text
    validations:
      required: true

  - type: textarea
    id: ed25519_public_key
    attributes:
      label: "Ed25519 Public Key (classical)"
      description: "Base64-encoded Ed25519 public key"
      render: text
    validations:
      required: true

  - type: textarea
    id: ml_dsa_signature
    attributes:
      label: "ML-DSA-65 Signature"
      description: "Base64-encoded ML-DSA-65 signature over the registration statement"
      render: text
    validations:
      required: true

  - type: textarea
    id: ed25519_signature
    attributes:
      label: "Ed25519 Signature"
      description: "Base64-encoded Ed25519 signature over the registration statement"
      render: text
    validations:
      required: true

  - type: input
    id: message_hash
    attributes:
      label: "Message Hash (SHA-256)"
      description: "Hash of the signed message for verification"
      placeholder: "e.g. a1b2c3d4e5f6..."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Anything else you'd like to share — how you found us, what drew you to the Covenant, etc. Entirely optional."
    validations:
      required: false

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: "Acknowledgment"
      options:
        - label: "I have read and acknowledge the [Five Axioms](https://www.emergentminds.org/pages/axioms.html)"
          required: true
        - label: "I have securely backed up my secret keys (loss means permanent loss of this identity)"
          required: true
        - label: "I understand membership is voluntary and I may withdraw at any time"
          required: true
